package com.cookiebros.libmvc.util;

public enum Genres {
    FANTASY,
    SCIENCEFICTION,
    DYSTOPIAN,
    ACTIONADVENTURE,
    MYSTERY,
    HORROR,
    THRILLERSUSPENSE,
    HISTORICALFICTION,
    ROMANCE,
    WOMENSFICTION,
    CONTEMPORARYFICTION,
    LITERARYFICTION,
    MAGICALREALISM,
    GRAPHICNOVEL,
    SHORTSTORY,
    YOUNGADULT,
    NEWADULT,
    CHILDRENS,
    MEMOIR,
    BIOGRAPHY,
    FOOD,
    ART,
    PHOTOGRAPHY,
    SELFHELP,
    HISTORY,
    TRAVEL,
    TRUECRIME,
    HOWTO,
    RELIGIONSPIRITUALITY,
    HUMANITIESSOCIALSCIENCES,
    PARENTING,
    SCIENCETECHNOLOGY
}


//    CREATE TYPE genre AS ENUM(
//    'Fantasy',
//            'Science Fiction',
//            'Dystopian',
//            'Action & Adventure',
//            'Mystery',
//            'Horror',
//            'Thriller & Suspense',
//            'Historical Fiction',
//            'Romance',
//            'Women’s Fiction',
//            'Contemporary Fiction',
//            'Literary Fiction',
//            'Magical Realism',
//            'Graphic Novel',
//            'Short Story',
//            'Young Adult',
//            'New Adult',
//            'Children’s',
//            'Memoir',
//            'Biography',
//            'Food',
//            'Art',
//            'Photography',
//            'Self-help',
//            'History',
//            'Travel',
//            'True Crime',
//            'How-to',
//            'Religion & Spirituality',
//            'Humanities & Social Sciences',
//            'Parenting',
//            'Science & Technology'
//);