CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       fio varchar(255) UNIQUE,
                       year_of_birth int CHECK (year_of_birth > 1900));

INSERT INTO Person(fio, year_of_birth) VALUES ('Admin', 1901);
INSERT INTO Person(fio, year_of_birth) VALUES ('Печенин Валерий Алексеевич', 1990);
INSERT INTO Person(fio, year_of_birth) VALUES ('Печенин Юрий Алексеевич', 1990);
INSERT INTO Person(fio, year_of_birth) VALUES ('Кузьмин Артемий Викторович', 1991);

SELECT * FROM Person;

DROP TABLE Person;


CREATE TABLE Book(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title varchar(255),
                     author varchar(255),
                     year_of_publishing int CHECK (year_of_publishing > 1600),
                     person_id int REFERENCES Person(id) ON DELETE SET NULL);


INSERT INTO Book(title, author, year_of_publishing, person_id)
VALUES('Таинственный остров', 'Жуль Верн', 1890, 1);
INSERT INTO Book(title, author, year_of_publishing, person_id)
VALUES('Три мушкетера', 'Александр Дюма', 1840, 1);
INSERT INTO Book(title, author, year_of_publishing, person_id)
VALUES('Гадкие Лебеди', 'Братья Стругацкие', 1960, 1);



SELECT * FROM Book;

DROP TABLE Book;