package com.cookiebros.libmvc.models;

import com.cookiebros.libmvc.util.Genres;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;


//CREATE TABLE Book(
//        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        title varchar(255) NOT NULL,
//        author varchar(255) NOT NULL,
//        year_of_publishing int CHECK (year_of_publishing > 1600),
//        main_genre varchar(50) NOT NULL DEFAULT 'ROMANCE',
//        rating real CHECK(rating > -1 and rating < 11)
//);


@Entity
@Table(name = "Book")
public class Book {
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(name = "title")
    private String title;
    @Column(name = "author")
    private String author;
    @Column(name = "year_of_publishing")
    private int yearOfPublishing;

    @Column(name = "main_genre")
    private Genres mainGenre;
    @Column(name = "rating")
    private Double rating;
    @OneToOne(mappedBy = "book")
    private BookInfo bookInfo;
    @OneToMany(mappedBy = "book")
    private List<BookInstance> bookInstances;
    @OneToOne(mappedBy = "book")
    private BookRating bookRating;




    public Book() {}

    public Book(String title, String author, int yearOfPublishing, Genres mainGenre, Double rating) {
        this.title = title;
        this.author = author;
        this.yearOfPublishing = yearOfPublishing;
        this.mainGenre = mainGenre;
        this.rating = rating;
    }


    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return author;
    }
    public void setAuthor(String author) {
        this.author = author;
    }
    public int getYearOfPublishing() {
        return yearOfPublishing;
    }
    public void setYearOfPublishing(int yearOfPublishing) {
        this.yearOfPublishing = yearOfPublishing;
    }
    public Genres getMainGenre() {
        return mainGenre;
    }
    public void setMainGenre(Genres mainGenre) {
        this.mainGenre = mainGenre;
    }
    public Double getRating() {
        return rating;
    }
    public void setRating(Double rating) {
        this.rating = rating;
    }


    public BookInfo getBookInfo() {
        return bookInfo;
    }
    public void setBookInfo(BookInfo bookInfo) {
        this.bookInfo = bookInfo;
    }


    public List<BookInstance> getBookInstances() {
        return bookInstances;
    }
    public void setBookInstances(List<BookInstance> bookInstances) {
        this.bookInstances = bookInstances;
    }
    public void addBookInstance(BookInstance bookInstance) {
        if (getBookInstances().isEmpty())
            setBookInstances(new ArrayList<>());
        bookInstances.add(bookInstance);
    }


    public BookRating getBookRating() {
        return bookRating;
    }
    public void setBookRating(BookRating bookRating) {
        this.bookRating = bookRating;
    }


    @Override
    public String toString() {
        return "Book{" +
                "title='" + title + '\'' +
                ", author='" + author + '\'' +
                '}';
    }
}