package com.cookiebros.libmvc.models;

import com.cookiebros.libmvc.util.Roles;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;

//CREATE TABLE Person(
//        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        email varchar(100) UNIQUE NOT NULL,
//        password varchar(150) NOT NULL,
//        first_name varchar(100) NOT NULL,
//        last_name varchar(100) NOT NULL,
//        year_of_birth smallint CHECK (year_of_birth > 1900 and year_of_birth < 2050),
//        role varchar(30) NOT NULL DEFAULT 'GUEST',
//        photo_path varchar(255)
//);

@Entity
@Table(name = "Person")
public class Person {
//    TODO
//    добавить активацию акка по email
//    https://www.youtube.com/watch?v=yBXs_gtSmUc&ab_channel=letsCode
//    добавить активацию акка через Google
//    https://www.youtube.com/watch?v=-ohlXEJeRX8&t=630s&ab_channel=letsCode

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(name = "email")
    private String email;
    @Column(name = "password")
    private String password;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "year_of_birth")
    private int yearOfBirth;
    @Column(name = "role")
    private Roles role;
    @Column(name = "photo_path")
    private String photoPath;


    @OneToMany(mappedBy = "owner", fetch = FetchType.LAZY)
    private List<BookInst> bookInstances;
    @OneToOne(mappedBy = "person", fetch = FetchType.LAZY)
    private BookRating bookRating;




    public Person () {}

    public Person(String email, String password, String firstName, String lastName, int yearOfBirth) {
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.yearOfBirth = yearOfBirth;
    }

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public int getYearOfBirth() {
        return yearOfBirth;
    }
    public void setYearOfBirth(int yearOfBirth) {
        this.yearOfBirth = yearOfBirth;
    }
    public Roles getRole() {
        return role;
    }
    public void setRole(Roles role) {
        this.role = role;
    }
    public String getPhotoPath() {
        return photoPath;
    }
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }



    public List<BookInst> getBookInstances() {
        return bookInstances;
    }

    public void setBookInstances(List<BookInst> bookInstances) {
        this.bookInstances = bookInstances;
    }

    public void addBookInst(BookInst bookInst) {
        if (getBookInstances().isEmpty())
            setBookInstances(new ArrayList<>());
        bookInstances.add(bookInst);
    }


    public BookRating getBookRating() {
        return bookRating;
    }
    public void setBookRating(BookRating bookRating) {
        this.bookRating = bookRating;
    }


    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", name='" + firstName + " " + lastName + '\'' +
                ", yearOfBirth=" + yearOfBirth +
                '}';
    }
}